### ISSUE TITLE
Changing default unruley.ruler setting overwrites all editor.rulers

### ISSUE THREAD

**Issue by datalot-369** [brennacodes/unruley#1]
**Describe the bug**
Whenever you save the settings.js file with the unruley.ruler propertie, the editor.rulers deletes whatever it has and sets only the specified at unruley.ruler. This is both a duplication of the value and an arbitrary decision/bug.

**Steps to Reproduce**
1. Go to settings.js
2. Set:
```
    "editor.rulers": [
        {"column": 72},
        {"column": 80},
        {"column": 100}
    ],
    "rulery.ruler": 100
```
4. `Ctrl` + `S`

**Expected behavior**
Only characters that cross the 100 limit get red-colored, no matter what other rulers are set.

**Actual behavior**
editor.rulers get overwritten.

**Configuration Info:**
 - Device: DELL Latitude 3380
 - OS: Fedora 40
 
```
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.11-300.fc40.x86_64
```

**Comment by brennacodes** [comment]
@datalot-369 Taking a look into this and your other submission now and will update once it's resolved.

**Comment by brennacodes** [comment]
Closing. Reference https://github.com/brennacodes/unruley/issues/2
