### ISSUE TITLE
 Unruley always draws in red the lowest ruler, not the default one

### ISSUE THREAD

**Issue by datalot-369** [brennacodes/unruley#2]
**Describe the bug**
Tittle says everything.

**Steps to Reproduce**
1. Go to settings.js
2. Set:
```
    "editor.rulers": [
        {"column": 72},
        {"column": 80},
        {"column": 100}
    ]
```
4. `Ctrl` + `S`

**What happened?**
Characters that cross the 72 limit get red-colored, instead of being only the ones that cross the 80 limit, which is the Unruley's default.
 
```
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.11-300.fc40.x86_64
```

**Comment by brennacodes** [comment]
@datalot-369 Thanks for raising the issue! Taking a look into this and your other submission now and will update once it's resolved.

**Comment by brennacodes** [comment]
Closing. This should be now be fixed. 

The new behavior alerts the user if there are pre-existing conflicting settings for rulers found, and asks the user which settings it would like to apply for use with Unruley.  The default ruler setting for Unruley is still 80 characters. Depending on your current settings, you may need to visit Unruley's settings and let it know which ruler length you'd like to use with the extension.
@datalot-369
